import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Layout({ children }) {
    return (
        <div className={styles.container}>
            <Head>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className='w-full md:w-1/2 mx-auto mt-10'>
                <h1 className='text-4xl lg:text-6xl font-bold mb-6 text-center'>
                    <Link href='/'><a><span className='text-blue-600'>Next.Js</span> Todo</a></Link>
                </h1>
                {children}
            </main>

            <footer className='text-center mt-6'>
                Created by <span className='font-bold'>Ashraful</span>
            </footer>
        </div >
    )
}